wav_path: "/home/patchethium/LJSpeech/wavs"
output_path: "/home/patchethium/LJSpeech/output"
variance_path: "/home/patchethium/PycharmProjects/MyTTS/data/LJSpeech-1.1/output"
mel_path: "/home/patchethium/LJSpeech/output/mel"
corpus_size: 13100
filter_length: 1024
num_mels: 80
num_freq: 1025
n_fft: 1024
hop_size: 256
win_size: 1024
sampling_rate: 22050
fmin: 0
fmax: 8000
max_wav_value: 32768.0
marks: ['', 'AA', 'AE', 'AH', 'AO', 'AW', 'AY', 'B', 'CH', 'D', 'DH', 'EH', 'ER', 'EY', 'F', 'G',
           'HH', 'IH', 'IY', 'JH', 'K', 'L', 'M', 'N', 'NG', 'OW', 'OY', 'P', 'R', 'S', 'SH', 'T',
           'TH', 'UH', 'UW', 'V', 'W', 'Y', 'Z', 'ZH', 'sil', 'sp', 'spn']