path:
  wav_path: "/home/patchethium/LJSpeech/wavs"
  output_path: "/home/patchethium/LJSpeech/output"
  variance_path: "/home/patchethium/PycharmProjects/MyTTS/data/LJSpeech-1.1/output"
  mel_path: "/home/patchethium/LJSpeech/output/mel"
  variance_phoneme_path: "/home/patchethium/LJSpeech/output/variance_phoneme.npy"
  vanilla_phoneme_path: "/home/patchethium/LJSpeech/output/vanilla_phoneme.npy"
  ckpt_path: "/home/patchethium/PycharmProjects/Clio-training/ckpt"
optimizer:
  lr: 0.001
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 100000
